version: '3.7'

services:
  node26:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        VERSION: 26
      tags:
        - okteto/node:26
        - ghcr.io/okteto/node:26

  node24:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        VERSION: 24
      tags:
        - okteto/node:24
        - ghcr.io/okteto/node:24
