services:
  golang1:
    build:
      context: .
      dockerfile: golang/Dockerfile
      args:
        VERSION: "1.26.5"
        CONTROLLER_GEN_VERSION: "v0.21.0"
      tags:
        - okteto/golang:1
        - okteto/golang:1.26
        - ghcr.io/okteto/golang:1
        - ghcr.io/okteto/golang:1.26

  golang1.25:
    build:
      context: .
      dockerfile: golang/Dockerfile
      args:
        VERSION: "1.25.12"
        # Need to override these because newer versions require the golang 1.26 toolchain
        CONTROLLER_GEN_VERSION: "v0.20.1"
        GOPLS_VERSION: "v0.21.1"
      tags:
        - okteto/golang:1.25
        - ghcr.io/okteto/golang:1.25
