version: '3.7'

services:
  dotnetcore6:
    build:
      context: .
      dockerfile: dotnetcore/Dockerfile
      args:
        VERSION: "6.0"
      tags:
        - okteto/dotnetcore:6
        - ghcr.io/okteto/dotnetcore:6
  dotnetcore8:
    build:
      context: .
      dockerfile: dotnetcore/Dockerfile
      args:
        VERSION: "8.0"
      tags:
        - okteto/dotnetcore:8
        - ghcr.io/okteto/dotnetcore:8

  dotnetcore10:
    build:
      x-bake:
        platforms: [ "linux/amd64","linux/arm64" ]
      context: .
      dockerfile: dotnetcore/Dockerfile
      args:
        VERSION: "10.0.401"
      tags:
        - 783314667363.dkr.ecr.eu-west-1.amazonaws.com/okteto/dotnetcore:10.0.401

  
