version: '3.7'

services:
  node24:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        VERSION: 24
      tags:
        - okteto/node:24
        - ghcr.io/okteto/node:24

  node22:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        VERSION: 22
      tags:
        - okteto/node:22
        - ghcr.io/okteto/node:22
